FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the port for the Streamlit app
EXPOSE 8501

# Define environment variable to ensure python outputs everything without buffering
ENV PYTHONUNBUFFERED 1

# Command to run the Streamlit application
CMD ["streamlit", "run", "app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
